import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  Header  from "@/components/layout/header";
import { SiteFooter } from "@/components/layout/site-footer";
import { getCurrentUser } from "@/lib/session";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function homeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getCurrentUser()
  return (
    <div className="">
      <Header
       session={session}
      />
      <main className="flex-1">
        {children}
      </main>
      <SiteFooter />
    </div >
  );
}